<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="go2w">
  <!-- Gloabal parameters -->
  <xacro:include filename="$(find go2w_description)/urdf/const.xacro"/>

  <xacro:property name="mesh_prefix" value="file://$(find go2w_description)/meshes" />

  <xacro:macro name="leg" params="prefix front left">

    <xacro:if value="${(front == True)}">
        <xacro:property name="front_sign" value=" 1" />
    </xacro:if>
    <xacro:if value="${(front == False)}">
        <xacro:property name="front_sign" value="-1" />
    </xacro:if>
    <xacro:if value="${(left == True)}">
        <xacro:property name="left_sign" value=" 1" />
    </xacro:if>
    <xacro:if value="${(left == False)}">
        <xacro:property name="left_sign" value="-1" />
    </xacro:if>
    
    <!-- Hip -->
    <link name="${prefix}_hip">
      <inertial>
        <origin xyz="${hip_com_x*front_sign} ${hip_com_y*left_sign} ${hip_com_z}" rpy="0 0 0" />
        <mass value="${hip_mass}" />
        <inertia ixx="${hip_ixx}" ixy="${hip_ixy*left_sign*front_sign}" ixz="${hip_ixz*front_sign}" iyy="${hip_iyy}" iyz="${hip_iyz*left_sign}" izz="${hip_izz}" />
      </inertial>
      <visual>
        <xacro:if value="${(left == True) and (front == True)}">
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </xacro:if>
        <xacro:if value="${(left == False) and (front == True)}">
            <origin rpy="${PI} 0 0" xyz="0 0 0"/>
        </xacro:if>
        <xacro:if value="${(left == True) and (front == False)}">
            <origin rpy="0 ${PI} 0" xyz="0 0 0"/>
        </xacro:if>
        <xacro:if value="${(left == False) and (front == False)}">
            <origin rpy="${PI} ${PI} 0" xyz="0 0 0"/>
        </xacro:if>
        <geometry>
          <mesh filename="${mesh_prefix}/hip.dae" />
        </geometry>
        <material name="深色橡胶_001-effect"><color rgba="0.6717055 0.6924257 0.7742702 1" /></material><material name="Material-effect"><color rgba="0.9 0.95 0.95 1" /></material>
      </visual>
      <collision>
        <origin rpy="${PI/2.0} 0 0" xyz="0 0.08 0" />
        <geometry>
            <cylinder length="${hip_length}" radius="${hip_radius}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_hip_joint" type="revolute">
      <origin xyz="${hip_offset_x*front_sign} ${hip_offset_y*left_sign} ${hip_offset_z}" rpy="0 0 0" />
      <parent link="base" />
      <child link="${prefix}_hip" />
      <axis xyz="1 0 0" />
      <xacro:if value="${(left == True)}">
        <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${hip_position_min}" upper="${hip_position_max}"/>
      </xacro:if>
      <xacro:if value="${(left == False)}">
        <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${-hip_position_max}" upper="${-hip_position_min}"/>
      </xacro:if>
    </joint>

    <!-- Thigh -->
    <link name="${prefix}_thigh">
      <inertial>
        <origin xyz="${thigh_com_x} ${thigh_com_y*left_sign} ${thigh_com_z}" rpy="0 0 0" />
        <mass value="${thigh_mass}" />
        <inertia ixx="${thigh_ixx}" ixy="${thigh_ixy*left_sign}" ixz="${thigh_ixz}" iyy="${thigh_iyy}" iyz="${thigh_iyz*left_sign}" izz="${thigh_izz}" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <xacro:if value="${left == True}">
              <mesh filename="${mesh_prefix}/thigh.dae" scale="1 1 1"/>
          </xacro:if>
          <xacro:if value="${left == False}">
              <mesh filename="${mesh_prefix}/thigh_mirror.dae" scale="1 1 1"/>
          </xacro:if>
        </geometry>
        <material name="深色橡胶_003-effect"><color rgba="0.6717055 0.6924257 0.7742702 1" /></material><material name="Material_009-effect"><color rgba="0.9 0.95 0.95 1" /></material>
      </visual>
      <collision>
        <origin rpy="0 ${PI/2.0} 0" xyz="0 0 ${thigh_offset_z}" />
        <geometry>
          <box size="${thigh_length} ${thigh_width} ${thigh_height}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_thigh_joint" type="revolute">
      <origin xyz="${thigh_offset_x} ${thigh_offset_y*left_sign} ${thigh_offset_z}" rpy="0 0 0" />
      <parent link="${prefix}_hip" />
      <child link="${prefix}_thigh" />
      <axis xyz="0 1 0" />
      <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}" lower="${thigh_position_min}" upper="${thigh_position_max}" />
    </joint>

    <!-- Calf -->
    <link name="${prefix}_calf">
      <inertial>
        <origin xyz="${calf_com_x} ${calf_com_y*left_sign} ${calf_com_z}" rpy="0 0 0" />
        <mass value="${calf_mass}" />
        <inertia ixx="${calf_ixx}" ixy="${calf_ixy*left_sign}" ixz="${calf_ixz}" iyy="${calf_iyy}" iyz="${calf_iyz*left_sign}" izz="${calf_izz}" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <xacro:if value="${left == True}">
              <mesh filename="${mesh_prefix}/calf.stl" />
            </xacro:if>
            <xacro:if value="${left == False}">
              <mesh filename="${mesh_prefix}/calf_mirror.stl" />
            </xacro:if>
        </geometry>
        <material name="">
          <color rgba="1 1 1 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 ${calf_rotation_p} 0" xyz="${calf_offset_x} 0 ${calf_offset_z}" />
        <geometry>
          <cylinder length="${calf_length}" radius="${calf_radius}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_calf_joint" type="revolute">
      <origin xyz="${calf_offset_x} ${calf_offset_y*left_sign} ${calf_offset_z}" rpy="0 0 0" />
      <parent link="${prefix}_thigh" />
      <child link="${prefix}_calf" />
      <axis xyz="0 1 0" />
      <limit lower="${calf_position_min}" upper="${calf_position_max}" effort="${calf_torque_max}" velocity="${calf_velocity_max}" />
    </joint>

    <!-- Calf lower -->
    <link name="${prefix}_calflower">
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${calf_lower_length}" radius="${calf_lower_radius}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_calflower_joint" type="fixed">
      <origin xyz="${calf_lower_offset_x} ${calf_lower_offset_y*left_sign} ${calf_lower_offset_z}" rpy="0 ${calf_lower_rotation_p} 0" />
      <parent link="${prefix}_calf" />
      <child link="${prefix}_calflower" />
      <axis xyz="0 0 0" />
    </joint>

    <!-- Calf flower 1 -->
    <link name="${prefix}_calflower1">
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${calf_lower1_length}" radius="${calf_lower1_radius}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_calflower1_joint" type="fixed">
      <origin xyz="${calf_lower1_offset_x} ${calf_lower1_offset_y*left_sign} ${calf_lower1_offset_z}" rpy="${calf_lower1_rotation_p}" />
      <parent link="${prefix}_calflower" />
      <child link="${prefix}_calflower1" />
      <axis xyz="0 0 0" />
    </joint>

    <!-- Foot motor -->
    <link name="${prefix}_foot_motor">
      <inertial>
        <origin xyz="${foot_motor_com_x} ${foot_motor_com_y} ${foot_motor_com_z}" rpy="0 0 0" />
        <mass value="${foot_motor_mass}" />
        <inertia ixx="${foot_motor_ixx}" ixy="${foot_motor_ixy*left_sign}" ixz="${foot_motor_ixz}" iyy="${foot_motor_iyy}" iyz="${foot_motor_iyz*left_sign}" izz="${foot_motor_izz}" />
      </inertial>
      <collision>
        <origin rpy="${PI/2.0} 0 0" xyz="0 0 0" />
        <geometry>
            <cylinder length="${foot_motor_length}" radius="${foot_motor_radius}" />
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_foot_motor_joint" type="fixed">
      <origin xyz="${foot_motor_offset_x} ${foot_motor_offset_y*left_sign} ${foot_motor_offset_z}" rpy="0 0.0 0" />
      <parent link="${prefix}_calf" />
      <child link="${prefix}_foot_motor" />
      <axis xyz="0 0 0" />
    </joint>

    <!-- Foot -->
    <link name="${prefix}_foot">
      <inertial>
        <origin xyz="${foot_com_x} ${foot_com_y} ${foot_com_z}" rpy="0 0 0" />
        <mass value="${foot_mass}" />
        <inertia ixx="${foot_ixx}" ixy="${foot_ixy}" ixz="${foot_ixz}" iyy="${foot_iyy}" iyz="${foot_iyz}" izz="${foot_izz}" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <xacro:if value="${left == True}">
            <mesh filename="${mesh_prefix}/left_wheel.dae" />
            </xacro:if>
            <xacro:if value="${left == False}">
            <mesh filename="${mesh_prefix}/right_wheel.dae" />
            </xacro:if>
        </geometry>
        <material name="">
          <color rgba="1 1 1 1" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0.0 0" />
        <geometry>
          <xacro:if value="${left == True}">
            <mesh filename="${mesh_prefix}/left_wheel.dae" />
            </xacro:if>
            <xacro:if value="${left == False}">
            <mesh filename="${mesh_prefix}/right_wheel.dae" />
            </xacro:if>
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_foot_joint" type="continuous">
      <origin xyz="${foot_offset_x} ${foot_offset_y*left_sign} ${foot_offset_z}" rpy="0 0 0" />
      <parent link="${prefix}_calf" />
      <child link="${prefix}_foot" />
      <axis xyz="0 1 0" />
        <limit effort="${foot_torque_max}" velocity="${foot_velocity_max}" />
    </joint>

    <!-- Gazebo ros2_control -->
    <ros2_control name="${prefix}" type="system">
      <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
      </hardware>

      <joint name="${prefix}_hip_joint">
        <command_interface name="effort">
          <!-- <param name="min">${hip_torque_min}</param>
          <param name="max">${hip_torque_max}</param> -->
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">${hip_init_position}</param>
        </state_interface>
        <state_interface name="velocity"/>
        <!-- <state_interface name="effort"/> -->
      </joint>
        
      <joint name="${prefix}_thigh_joint">
        <command_interface name="effort">
          <!-- <param name="min">${thigh_torque_min}</param>
          <param name="max">${thigh_torque_max}</param> -->
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">${thigh_init_position}</param>
        </state_interface>
        <state_interface name="velocity"/>
        <!-- <state_interface name="effort"/> -->
      </joint>
        
      <joint name="${prefix}_calf_joint">
        <command_interface name="effort">
          <!-- <param name="min">${calf_torque_min}</param>
          <param name="max">${calf_torque_max}</param> -->
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">${calf_init_position}</param>
        </state_interface>
        <state_interface name="velocity"/>
        <!-- <state_interface name="effort"/> -->
      </joint>

      <joint name="${prefix}_foot_joint">
        <command_interface name="effort">
          <!-- <param name="min">-100.0</param>
          <param name="max">100.0</param> -->
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">0.0</param>
        </state_interface>
        <state_interface name="velocity"/>
        <!-- <state_interface name="effort"/> -->
      </joint>
    </ros2_control>

  </xacro:macro>

  <link name="base">
    <inertial>
      <origin xyz="${base_com_x} ${base_com_y} ${base_com_z}" rpy="0 0 0" />
      <mass value="${base_mass}" />
      <inertia ixx="${base_ixx}" ixy="${base_ixy}" ixz="${base_ixz}" iyy="${base_iyy}" iyz="${base_iyz}" izz="${base_izz}" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="${mesh_prefix}/base.dae" />
      </geometry>
      <material name="深色橡胶_001-effect"><color rgba="0.6717055 0.6924257 0.7742702 1" /></material><material name="白色logo_001-effect"><color rgba="1 1 1 1" /></material><material name="黑色贴纸_007-effect"><color rgba="0.009018 0.009018 0.009018 1" /></material><material name="黑色金属_007-effect"><color rgba="0.01341 0.01341 0.01341 1" /></material><material name="黑色塑料_003-effect"><color rgba="0.023455 0.023455 0.023455 1" /></material></visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <geometry>
        <box size="${base_length} ${base_width} ${base_width}" />
      </geometry>
    </collision>
  </link>
  <link name="Head_upper">
    <inertial>
      <origin xyz="${head_upper_com_x} ${head_upper_com_y} ${head_upper_com_z}" rpy="0 0 0" />
      <mass value="${head_upper_mass}" />
      <inertia ixx="${head_upper_ixx}" ixy="${head_upper_ixy}" ixz="${head_upper_ixz}" iyy="${head_upper_iyy}" iyz="${head_upper_iyz}" izz="${head_upper_izz}" />
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${head_upper_radius}" length="${head_upper_length}" />
      </geometry>
    </collision>
  </link>
  <joint name="Head_upper_joint" type="fixed" dont_collapse="true">
    <origin xyz="0.285 0 0.01" rpy="0 0 0" />
    <parent link="base" />
    <child link="Head_upper" />
    <axis xyz="0 0 0" />
  </joint>
  <link name="Head_lower">
    <inertial>
      <origin xyz="${head_lower_com_x} ${head_lower_com_y} ${head_lower_com_z}" rpy="0 0 0" />
      <mass value="${head_lower_mass}" />
      <inertia ixx="${head_lower_ixx}" ixy="${head_lower_ixy}" ixz="${head_lower_ixz}" iyy="${head_lower_iyy}" iyz="${head_lower_iyz}" izz="${head_lower_izz}" />
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${head_lower_radius}" />
      </geometry>
    </collision>
  </link>
  <joint name="Head_lower_joint" type="fixed" dont_collapse="true">
    <origin xyz="0.008 0 -0.07" rpy="0 0 0" />
    <parent link="Head_upper" />
    <child link="Head_lower" />
    <axis xyz="0 0 0" />
  </joint>
  
  <xacro:leg prefix="FL" front="True" left="True"/>
  <xacro:leg prefix="FR" front="True" left="False"/>
  <xacro:leg prefix="RL" front="False" left="True"/>
  <xacro:leg prefix="RR" front="False" left="False"/>

  <link name="imu">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0" />
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>
  </link>
  <joint name="imu_joint" type="fixed">
    <origin xyz="-0.02557 0 0.04232" rpy="0 0 0" />
    <parent link="base" />
    <child link="imu" />
    <axis xyz="0 0 0" />
  </joint>
  <link name="radar">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0" />
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>
  </link>
  <joint name="radar_joint" type="fixed">
    <origin xyz="0.28945 0 -0.046825" rpy="0 2.8782 0" />
    <parent link="base" />
    <child link="radar" />
    <axis xyz="0 0 0" />
  </joint>

  <gazebo>
      <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <parameters>$(find go2w_description)/config/joint_controller.yaml</parameters>
    </plugin>
  </gazebo>
</robot>